CREATE TABLE PAYMENT_METHOD
(
    ID                    BIGSERIAL PRIMARY KEY,
    NAME                  VARCHAR(50) NOT NULL,
    PRICE_MULTIPLIER_FROM DOUBLE PRECISION,
    PRICE_MULTIPLIER_TO   DOUBLE PRECISION,
    POINTS_MULTIPLIER     DOUBLE PRECISION,
    ID_RULE               BIGINT      NOT NULL,
    ACTIVE                BOOLEAN
);

CREATE TABLE RULE
(
    ID                          BIGSERIAL PRIMARY KEY,
    NAME                        VARCHAR(50) NOT NULL,
    STORE_CREDIT_CARD_LAST_FOUR BOOLEAN,
    STORE_BANK_CODE             BOOLEAN,
    STORE_ACCOUNT_NUMBER        BOOLEAN,
    STORE_CHECK_NUMBER          BOOLEAN,
    VALIDATE_COURIER            BOOLEAN,
    DESCRIPTION                 VARCHAR(250)
);

CREATE TABLE COURIER
(
    ID          BIGSERIAL PRIMARY KEY,
    NAME        VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(250)
);

CREATE TABLE COURIER_RULE
(
    ID          BIGSERIAL PRIMARY KEY,
    ID_RULE     BIGINT NOT NULL,
    ID_COURIER  BIGINT NOT NULL,
    DESCRIPTION VARCHAR(250),
    FOREIGN KEY (ID_RULE) REFERENCES RULE (ID),
    FOREIGN KEY (ID_COURIER) REFERENCES COURIER (ID)
);

CREATE TABLE PAYMENT
(
    ID                BIGSERIAL PRIMARY KEY,
    ID_PAYMENT_METHOD BIGINT      NOT NULL,
    INITIAL_PRICE     DOUBLE PRECISION,
    FINAL_PRICE       DOUBLE PRECISION,
    PRICE_MODIFIER    DOUBLE PRECISION,
    POINTS_MULTIPLIER DOUBLE PRECISION,
    POINTS            INTEGER,
    ID_CUSTOMER       VARCHAR(36) NOT NULL,
    DATETIME          TIMESTAMP WITH TIME ZONE,
    CREDIT_CARD_LAST_FOUR VARCHAR(4),
    BANK_CODE VARCHAR(10),
    ACCOUNT_NUMBER VARCHAR(15),
    CHECK_NUMBER VARCHAR(20),
    COURIER VARCHAR(20),
    FOREIGN KEY (ID_PAYMENT_METHOD) REFERENCES PAYMENT_METHOD(ID)
);
