INSERT INTO PAYMENT_METHOD (ID, NAME, PRICE_MULTIPLIER_FROM, PRICE_MULTIPLIER_TO, POINTS_MULTIPLIER, ID_RULE, ACTIVE)
VALUES
    (NEXTVAL('PAYMENT_METHOD_SEQ'), 'CASH', 0.9, 1, 0.05, (SELECT ID FROM RULE WHERE NAME = 'CASH'), TRUE),
    (NEXTVAL('PAYMENT_METHOD_SEQ'), 'CASH_ON_DELIVERY', 1, 1.02, 0.05, (SELECT ID FROM RULE WHERE NAME = 'ON_DELIVERY'), TRUE),
    (NEXTVAL('PAYMENT_METHOD_SEQ'), 'VISA', 0.95, 1, 0.03, (SELECT ID FROM RULE WHERE NAME = 'CREDIT_CARD'), TRUE),
    (NEXTVAL('PAYMENT_METHOD_SEQ'), 'MASTERCARD', 0.95, 1, 0.03, (SELECT ID FROM RULE WHERE NAME = 'CREDIT_CARD'), TRUE),
    (NEXTVAL('PAYMENT_METHOD_SEQ'), 'AMEX', 0.98, 1.01, 0.02, (SELECT ID FROM RULE WHERE NAME = 'CREDIT_CARD'), TRUE),
    (NEXTVAL('PAYMENT_METHOD_SEQ'), 'JCB', 0.95, 1, 0.05, (SELECT ID FROM RULE WHERE NAME = 'CREDIT_CARD'), TRUE),
    (NEXTVAL('PAYMENT_METHOD_SEQ'), 'LINE_PAY', 1, 1, 0.01, (SELECT ID FROM RULE WHERE NAME = 'ONLINE_PAYMENT'), TRUE),
    (NEXTVAL('PAYMENT_METHOD_SEQ'), 'PAYPAY', 1, 1, 0.01, (SELECT ID FROM RULE WHERE NAME = 'ONLINE_PAYMENT'), TRUE),
    (NEXTVAL('PAYMENT_METHOD_SEQ'), 'POINTS', 1, 1, 0, (SELECT ID FROM RULE WHERE NAME = 'CASH'), TRUE),
    (NEXTVAL('PAYMENT_METHOD_SEQ'), 'GRAB_PAY', 1, 1, 0.01, (SELECT ID FROM RULE WHERE NAME = 'ONLINE_PAYMENT'), TRUE),
    (NEXTVAL('PAYMENT_METHOD_SEQ'), 'BANK_TRANSFER', 1, 1, 0, (SELECT ID FROM RULE WHERE NAME = 'BANK_TRANSFER'), TRUE),
    (NEXTVAL('PAYMENT_METHOD_SEQ'), 'CHEQUE', 0.9, 1, 0, (SELECT ID FROM RULE WHERE NAME = 'CHEQUE'), TRUE);
